import { 
    riceOrLettuce, 
    redOrGreen, 
    tacoModifiers,
    bowlModifiers,
    nachosModifiers,
    pizzadillaModifiers,
    smallOrLarge,
    guacSize,
    sodas,
} from './modifiers';
import specials from './specials';

const foodList = [
    // Mexican Tacos
    {
        id: 1, 
        name: 'Carne Asada', 
        categoryID: 1,
        desc: 'Grilled steak, onions, cilantro, Tony\'s sauce',
        price: 4.50,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    {
        id: 2, 
        name: 'Pollo Asado', 
        categoryID: 1,
        desc: 'Shredded chicken, onions, cilantro, Tony\'s sauce',
        price: 3.50,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    {
        id: 3, 
        name: 'Pulled Pork', 
        categoryID: 1,
        desc: 'Pulled pork, onions, cilantro, Tony\'s sauce',
        price: 3.50,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    {
        id: 4, 
        name: 'Chorizo', 
        categoryID: 1,
        desc: 'Mexican sausage, onions, cilantro, Tony\'s sauce',
        price: 3.50,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    {
        id: 5, 
        name: 'Shrimp', 
        categoryID: 1,
        desc: 'Grilled shrimp, onions, cilantro, Tony\'s sauce',
        price: 4.50,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    {
        id: 6, 
        name: 'Cauliflower', 
        categoryID: 1,
        desc: 'Roasted cauliflower, onions, cilantro, Tony\'s sauce',
        price: 3.50,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    {
        id: 7, 
        name: 'Barbacoa', 
        categoryID: 1,
        desc: 'Shredded beef, onions, cilantro, Tony\'s sauce',
        price: 4.00,
        modifiers: tacoModifiers,
        choices: redOrGreen,
    },
    // Italian Tacos
    {
        id: 8, 
        name: 'Chorizo & Rabe', 
        categoryID: 2,
        desc: 'Mexican sausage, lava cheese, broccoli rabe, cherry peppers',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 9, 
        name: 'Chicken Parm', 
        categoryID: 2,
        desc: 'Fried chicken cutlet, lava cheese, tomato sauce',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 10, 
        name: 'Philly Cheesesteak Taco', 
        categoryID: 2,
        desc: 'Cheesesteak, carmalized onions, roasted red peppers',
        price: 5.50,
        modifiers: tacoModifiers,
    },
    {
        id: 11, 
        name: 'Steak & Cheese', 
        categoryID: 2,
        desc: 'Grilled steak, lava cheese, roasted red peppers',
        price: 5.50,
        modifiers: tacoModifiers,
    },
    {
        id: 12, 
        name: 'Cheese Ravioli', 
        categoryID: 2,
        desc: 'Ravioli, lava cheese, tomato sauce',
        price: 4.50,
        modifiers: tacoModifiers,
    },
    {
        id: 13, 
        name: 'Shrimp & Arugula', 
        categoryID: 2,
        desc: 'Grilled shrimp, arugula, pico de gallo, fresh squeezed lime',
        price: 5.50,
        modifiers: tacoModifiers,
    },
    {
        id: 14, 
        name: 'Chicken & Mango Jalapeno', 
        categoryID: 2,
        desc: 'Shredded chicken, mango, jalapeno, cilantro, Tony\'s green sauce',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 15, 
        name: 'Eggplant Plancha', 
        categoryID: 2,
        desc: 'Grilled steak, marinated eggplant, parsley',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 16, 
        name: 'Beef & Beens', 
        categoryID: 2,
        desc: 'Shredded beef, corn, black beans, lava cheese, cilantro, jalapeno',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 17, 
        name: 'Sausage & Peppers', 
        categoryID: 2,
        desc: 'Sausage, lava cheese, roasted red peppers',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 18, 
        name: 'Hot Dog & Fries', 
        categoryID: 2,
        desc: 'Hot dog, lava cheese, fries, spicy mayo',
        price: 4.50,
        modifiers: tacoModifiers,
    },
    {
        id: 19, 
        name: 'Brussels Taco', 
        categoryID: 2,
        desc: 'Brussel sprouts, caramelized onions, Tony\'s red sauce, sour cream',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 20, 
        name: 'Shrimp & Mango', 
        categoryID: 2,
        desc: 'Grilled shrimp, mango, rice, spicy mayo',
        price: 5.50,
        modifiers: tacoModifiers,
    },
    {
        id: 21, 
        name: 'Genovese', 
        categoryID: 2,
        desc: 'Shredded beef, onion sauce, parsley, parmigiano',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 22, 
        name: 'Chicken Club', 
        categoryID: 2,
        desc: 'Fried chicken cutlet, pico de gallo, lettuce, shredded cheese, spicy mayo',
        price: 5.50,
        modifiers: tacoModifiers,
    },
    {
        id: 23, 
        name: 'Butternut Squash Burrata', 
        categoryID: 2,
        desc: 'Butternut squash, burrata, red beans, burrata, cayenne, cinnamon',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 24, 
        name: 'Chili Taco', 
        categoryID: 2,
        desc: 'Italian veggie red bean chili, rice',
        price: 4.50,
        modifiers: tacoModifiers,
    },
    {
        id: 25, 
        name: 'Autumn Chicken', 
        categoryID: 2,
        desc: 'Shredded chicken, butternut squash, brussels, shredded cheese',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 26, 
        name: 'Octopus Taco', 
        categoryID: 2,
        desc: 'grilled octopus, diced potato, beans, greek yogurt',
        price: 6.00,
        modifiers: tacoModifiers,
    },
    {
        id: 27, 
        name: 'Bacala Taco', 
        categoryID: 2,
        desc: 'Fried cod bites, broccoli rabe, cherry pepper aioli',
        price: 6.00,
        modifiers: tacoModifiers,
    },
    {
        id: 28, 
        name: 'Chicken Peperonata', 
        categoryID: 2,
        desc: 'Shredded chicken, carmalized onion, red pepper, diced potato, sour cream',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    {
        id: 29, 
        name: 'Cauli Explosion', 
        categoryID: 2,
        desc: 'Melted mozzarella tortilla, roasted cauliflower, lava cheese',
        price: 5.00,
        modifiers: tacoModifiers,
    },
    // Tasty Plates
    {
        id: 30, 
        name: 'Mexican Wings', 
        categoryID: 3,
        desc: '8 crispy wings with side of buffalo and jalapeno ranch',
        price: 9.95,
    },
    {
        id: 31, 
        name: 'Nachos', 
        categoryID: 3,
        desc: 'Tortilla chips, jalapeno, pico de gallo, lava cheese, sour cream',
        price: 7.00,
        modifiers: nachosModifiers,
    },
    {
        id: 32, 
        name: 'Nachos Supreme', 
        categoryID: 3,
        desc: 'Tortilla chips, jalapeno, pico de gallo, lava cheese, sour cream, black beans, corn',
        price: 9.00,
        modifiers: nachosModifiers,
    },
    {
        id: 33, 
        name: 'Nacho Fries', 
        categoryID: 3,
        desc: 'French fries, jalapeno, pico de gallo, lava cheese, sour cream',
        price: 9.00,
        modifiers: nachosModifiers,
    },
    {
        id: 34, 
        name: 'Veggie Chili', 
        categoryID: 3,
        desc: '16oz Italian red bean chili',
        price: 6.00,
    },
    {
        id: 35, 
        name: 'Queso Dip', 
        categoryID: 3,
        desc: '8oz lava cheese and tortilla chips',
        price: 6.00,
    },
    {
        id: 36, 
        name: 'Holy Guacamole', 
        categoryID: 3,
        desc: 'Guacamole and tortilla chips',
        price: 0.00,
        choices: guacSize,
    },
    {
        id: 37, 
        name: 'Rice & Beans', 
        categoryID: 3,
        desc: 'White rice and black beans',
        price: 5.00,
        modifiers: bowlModifiers,
    },
    {
        id: 38, 
        name: 'French Fries', 
        categoryID: 3,
        desc: 'Side of fries',
        price: 4.95,
    },
    {
        id: 39, 
        name: 'Pollos & Papas', 
        categoryID: 3,
        desc: 'Chicken fingers & french fries',
        price : 9.00,
    },
    {
        id: 40, 
        name: 'Cod Nuggets', 
        categoryID: 3,
        desc: '6 cod nuggets, cherry pepper mayo on the side',
        price: 7.95,
    },
    {
        id: 41, 
        name: 'Mex Bowl', 
        categoryID: 3,
        desc: 'Rice or lettuce, black beans, guac, shredded beef, sour cream, Tony\'s red sauce',
        price: 9.95,
        modifiers: bowlModifiers,
        choices: riceOrLettuce,
        image: require('../assets/images/mexBowl.png'),
    },
    {
        id: 42, 
        name: 'Cauliflower & Brussels Bowl', 
        categoryID: 3,
        desc: 'Rice or lettuce, cauliflower, brussel sprouts, caramelized onions, sour cream, Tony\'s red sauce',
        price: 10.95,
        modifiers: bowlModifiers,
        choices: riceOrLettuce,
    },
    {
        id: 43, 
        name: 'Short Ribs', 
        categoryID: 3,
        desc: '2 peices of short ribs over rice',
        price: 10.95,
    },
    {
        id: 44, 
        name: 'Spanish Octopus', 
        categoryID: 3,
        desc: 'Grilled octopus, leg with potato, beans, side of greek yogurt',
        price: 13.95,
    },
    // Pizzadillas
    {
        id: 45, 
        name: 'Fra Diavolo', 
        categoryID: 4,
        desc: 'Tomato sauce, burrata, spicy pepper',
        price: 10.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 46, 
        name: 'Chef Mike', 
        categoryID: 4,
        desc: 'White pizzadilla, burrata, marinated eggplant',
        price: 13.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 47, 
        name: 'Buffalo', 
        categoryID: 4,
        desc: 'Mozzarella, buffalo chicken, bleu cheese',
        price: 11.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 48, 
        name: 'Buffalo Cauliflower', 
        categoryID: 4,
        desc: 'Buffalo cauliflower, mozzarella, bleu cheese',
        price: 11.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 49, 
        name: 'El Jefe', 
        categoryID: 4,
        desc: 'Barbacoa, black beans, corn, lava cheese, pico de gallo',
        price: 12.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 50, 
        name: 'Brussels Pizza', 
        categoryID: 4,
        desc: 'Mozzarella, roasted brussels, back beans, parmiggiano',
        price: 12.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 51, 
        name: 'Regular', 
        categoryID: 4,
        desc: 'Tomato sauce, mozzarella, parmiggiano',
        price: 9.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 52, 
        name: 'Chorzo & Rabe Pizza', 
        categoryID: 4,
        desc: 'Chorizo, borcoli rabe, lava cheese',
        price: 12.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 53, 
        name: 'Chicken & Fries', 
        categoryID: 4,
        desc: 'Fried chicken cutlet, mozzarella, fries, lava cheese',
        price: 12.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 54, 
        name: 'Squash Pizza', 
        categoryID: 4,
        desc: 'Butternut squash, mozzarella, red beads, cayenne, cinnamon',
        price: 12.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 55, 
        name: 'Chef Joel', 
        categoryID: 4,
        desc: 'Black beans, corn, red pepper, jalapeno, lava cheese',
        price: 11.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 56, 
        name: 'Chicken', 
        categoryID: 4,
        desc: 'Shredded chicken, mozzarella, lava cheese',
        price: 11.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 57, 
        name: 'Philly Cheesesteak', 
        categoryID: 4,
        desc: 'Stuffed tortilla crust with philly cheesesteak, broccoli rabe, peppers, onions',
        price: 14.00,
        modifiers: pizzadillaModifiers,
    },
    {
        id: 58, 
        name: 'Seafood Pizza', 
        categoryID: 4,
        desc: 'Mozzarella, pico de gallo, octopus, shrimp, red beans',
        price: 15.00,
        modifiers: pizzadillaModifiers,
    },
    // Desserts
    {
        id: 59, 
        name: 'Churros Dulce De Leche', 
        categoryID: 5,
        desc: '2 churros filled with dulce de leche and drizzled with nutella',
        price: 7.00,
    },
    {
        id: 60, 
        name: 'Nutella Crepes', 
        categoryID: 5,
        desc: 'Crepes filled with nutella',
        price: 7.00,
    },
    // Beverages
    {
        id: 61, 
        name: 'Mango Juice', 
        categoryID: 6,
        desc: 'Fresh squeezed mango juice',
        price: 0.00,
        choices: smallOrLarge,
    },
    {
        id: 62, 
        name: 'Passion Fruit Juice', 
        categoryID: 6,
        desc: 'Fresh squeezed passion fruit juice',
        price: 0.00,
        choices: smallOrLarge,
    },
    {
        id: 63, 
        name: 'Blueberry Lemonade', 
        categoryID: 6,
        desc: 'Lemonade with fresh squeezed blueberries',
        price: 0.00,
        choices: smallOrLarge,
    },
    {
        id: 64, 
        name: 'Bottle of Water', 
        categoryID: 6,
        desc: 'Bottled water',
        price: 1.50,
    },
    {
        id: 65, 
        name: 'Bottled Sodas & Iced Tea', 
        categoryID: 6,
        desc: 'Drinks',
        price: 2.25,
        choices: sodas,
    },
    // Margaritas
    {
        id: 66, 
        name: 'Classic Margarita', 
        categoryID: 7,
        desc: 'Lemon and lime juice margarita',
        price: 9.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 67, 
        name: 'Mango Margarita', 
        categoryID: 7,
        desc: 'Mango juice margarita',
        price: 9.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 68, 
        name: 'Passion Fruit Margarita', 
        categoryID: 7,
        desc: 'Passion fruit margarita',
        price: 9.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 69, 
        name: 'Guava Margarita', 
        categoryID: 7,
        desc: 'Guava juice margarita',
        price: 9.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 70, 
        name: 'Spicy Margarita', 
        categoryID: 7,
        desc: 'Classica margarita with crushed jalapenos',
        price: 9.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 71, 
        name: 'Aperol Margarita', 
        categoryID: 7,
        desc: 'Margarita with the Italian liqour: Aperol',
        price: 9.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 72, 
        name: 'Frozen Mango Margarita', 
        categoryID: 7,
        desc: 'Frozen mango juice margarita',
        price: 10.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    },
    {
        id: 73, 
        name: 'Frozen Gummy Bear Margarita', 
        categoryID: 7,
        desc: 'Frozen margarita with tequila soaked gummy bears, guava and passion fruit juice',
        price: 10.00,
        modifiers: [
            {
                id: 1,
                name: "Extra shot",
                price: 3.00
            }
        ],
    }
];

var foodListLen = foodList.length;

for (var i = 0; i < specials.length; i++) {
    specials[i].id += foodListLen;
    foodList.push(specials[i]);
}

export default foodList;